from dataclasses import dataclass
from typing import List
from datetime import datetime

@dataclass
class VectorEmbedding:
    """
    Numerical representation of a content chunk generated by the Cohere embedding model.
    """
    vector_id: str
    vector_data: List[float]
    chunk_id: str
    model_used: str
    created_at: datetime

    def __post_init__(self):
        """Validate the embedding after initialization."""
        if len(self.vector_data) != 1024:  # Expected size based on configuration
            raise ValueError(f"Vector data must have 1024 dimensions, got {len(self.vector_data)}")

        if not self.model_used:
            raise ValueError("Model used is required")

        if not self.chunk_id:
            raise ValueError("Chunk ID is required")