import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'doc',
      id: 'preface',
    },
    {
      type: 'doc',
      id: 'glossary',
    },
    {
      type: 'doc',
      id: 'appendices',
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics',
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-extras',
    },
    {
      type: 'category',
      label: 'Module 1 — The Robotic Nervous System (ROS 2)',
      link: { type: 'doc', id: 'modules/module-1/index' },
      items: [
        'modules/module-1/module-1-summary',
        'modules/module-1/chapter-1-intro-ros2',
        'modules/module-1/chapter-2-ros2-setup',
        'modules/module-1/chapter-3-ros2-comm',
        'modules/module-1/chapter-4-python-rclpy',
        'modules/module-1/chapter-5-urdf',
        'modules/module-1/chapter-6-mini-project',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
